makefile check prerequisties fixups

diff --git a/ThirdPartyLibs/curl/Makefile b/ThirdPartyLibs/curl/Makefile
--- a/ThirdPartyLibs/curl/Makefile
+++ b/ThirdPartyLibs/curl/Makefile
@@ -119,8 +119,7 @@ else
 		echo "      ...Building libcurl $(TRGDIR)...";\
 		echo "         ...into $(BUILDS_DIR)...";\
 		echo "         ...checking tools...";\
-		type automake > /dev/null || echo "......Missing automake";\
-		type libtool > /dev/null || echo "......Missing libtool";\
+		$(MAKE) --no-print-directory check_prerequisites_;\
 		echo "         ...see $(shell pwd)/CURRENT/BUILD-CONFIG.OUT for details...";\
 		cd CURRENT;\
 		./buildconf > BUILD-CONFIG.OUT 2>&1;\
@@ -138,6 +137,12 @@ ifeq (Unix,$(ProjectPlatformSubdir))
 else
 	@todo - INCOMPLETE WINDOZE BUILD
 endif
+
+
+check_prerequisites_:
+	@type automake > /dev/null || echo "......Missing automake";\
+	@type libtool > /dev/null || echo "......Missing libtool";\
+
 
 check:
 	@##THMPHACK
diff --git a/ThirdPartyLibs/lzma/Makefile b/ThirdPartyLibs/lzma/Makefile
--- a/ThirdPartyLibs/lzma/Makefile
+++ b/ThirdPartyLibs/lzma/Makefile
@@ -84,6 +84,8 @@ $(PRODUCED_OUTPUT_ARTIFACTS):	$(TRGDIR)/Builds
 	
 $(TRGDIR)/Builds:
 	@echo "   Building Stroika/ThirdPartyLibs/lzma $(VERSION)..."
+	@echo "         ...checking tools..."
+	@$(MAKE) --no-print-directory check_prerequisites_
 	@$(MAKE) --no-print-directory doCreate
 	@$(MAKE) --no-print-directory doBuilds
 
@@ -96,12 +98,18 @@ $(TRGDIR):	$(ZIPPEDFILE)
 	@$(MAKE) --no-print-directory doCreate
 
 
+
+check_prerequisites_:
+	@type 7za > /dev/null || echo "......Missing 7za";\
+
+
+
 doCreate:	$(ZIPEDFILE)
 	@if [ -e  $(TRGDIR) ]; then\
 		echo "      ...$(TRGDIR) dir already exists";\
 	else\
 		echo "      ...Extract $(ZIPEDFILE) to $(TRGDIR)...";\
-		7z x -o$(TRGDIR) $(ZIPEDFILE) > /dev/null;\
+		7za x -o$(TRGDIR) $(ZIPEDFILE) > /dev/null;\
 		cp Subdir-Makefile $(TRGDIR)/Makefile;\
 	fi
 
