updated makefile for libcurl to print better error messages about missing automake and libcurl

diff --git a/ThirdPartyLibs/curl/Makefile b/ThirdPartyLibs/curl/Makefile
--- a/ThirdPartyLibs/curl/Makefile
+++ b/ThirdPartyLibs/curl/Makefile
@@ -70,7 +70,10 @@ else
 	@if [ -e  $(BUILDS_DIR) ]; then\
 		echo "   ...Libcurl in $(BUILDS_DIR) complete";\
 	else\
-		echo "   ...Building libcurl $(TRGDIR) into $(BUILDS_DIR): SEE $(shell pwd)/CURRENT/BUILD-CONFIG.OUT for details...";\
+		echo "   ...Building libcurl $(TRGDIR)...checking tools...";\
+		type automake > /dev/null || echo "......Missing automake";\
+		type libtool > /dev/null || echo "......Missing libtool";\
+		echo "   ...Building into $(BUILDS_DIR): SEE $(shell pwd)/CURRENT/BUILD-CONFIG.OUT for details...";\
 		cd CURRENT;\
 		./buildconf > BUILD-CONFIG.OUT 2>&1;\
 		echo "   ...TODO - fix to use my copy of ssl, if we build SSL...";\
