fixed ScriptsLib/ResolveIP for windows

diff --git a/ScriptsLib/ResolveIP b/ScriptsLib/ResolveIP
--- a/ScriptsLib/ResolveIP
+++ b/ScriptsLib/ResolveIP
@@ -4,4 +4,12 @@
 # because I cannot figure out how to get docker containers to resolve local hostnames
 # 	# (like raspberrypi.local) to ip addresses
 HOSTNAME=$1
-ping -q -c 1 -t 1 $HOSTNAME | grep PING | sed -e "s/).*//" | sed -e "s/.*(//"
+R=`ping -q -c 1 -t 1 $HOSTNAME | grep PING | sed -e "s/).*//" | sed -e "s/.*(//"`
+if [ -z "$R" ]; then
+    R=`ping -4 -n 1 -w 1 $HOSTNAME | tail +2 | head -1 | sed -nE 's/.*\[(.*)\].*/\1/p'`
+fi
+if [ -z "$R" ]; then
+    echo "Error: Unable to resolve hostname $HOSTNAME"
+    exit 1
+fi
+echo $R
