tiny bit of progress on make skel but along way togo

diff --git a/Samples/Makefile b/Samples/Makefile
--- a/Samples/Makefile
+++ b/Samples/Makefile
@@ -11,9 +11,9 @@ CONFIGRUATIONS=		DefaultConfiguration
 endif
 
 
-SKEL_SRCPROJDIR=WebServer
-SKEL_TRGPROJName=Clone-Of-$(SKEL_SRCPROJDIR)
-
+SKEL_SRCPROJDIR?=
+SKEL_TRGPROJDir?=
+SKEL_TRGPROJName?=
 
 help:
 	@echo "Help for making Stroika"
@@ -41,14 +41,36 @@ clobber:
 samples:
 	@perl buildall.pl build
 
+
+skel-usage_:
+	@echo "\tUsage: make skel SKEL_SRCPROJDIR=XX SKEL_TRGPROJDIR=XX SKEL_TRGPROJName=XX"
+	@echo "\t\tSKEL_SRCPROJDIR is the sample you wisht to clone"
+	@echo "\t\tEG: make skel SKEL_SRCPROJDIR=WebServer SKEL_TRGPROJDIR=./SAMPLEOUT SKEL_TRGPROJName=CLONED_WS"
+
 skel:
-	@if [ -e "$(SKEL_TRGPROJName)" ]; then\
-	  echo "make skel FAILED because directory $(SKEL_TRGPROJName) already exists";\
-	  exit 1;\
-	else\
-	  cp -r $(SKEL_SRCPROJDIR) $(SKEL_TRGPROJName);\
-	  mkdir -p $(SKEL_TRGPROJName)/IntermediateFiles/DefaultConfiguration;\
-	  ln -s ../../Projects/Linux/Makefile $(SKEL_TRGPROJName)/IntermediateFiles/DefaultConfiguration/Makefile;\
-	  cp Skel/Makefile.skel $(SKEL_TRGPROJName)/Projects/Linux/Makefile;\
+	@if [ "$(SKEL_SRCPROJDIR)" = "" ]; then\
+		echo "make skel FAILED: need SKEL_SRCPROJDIR";\
+	 	$(MAKE) --no-print-directory skel-usage_;\
+	 	exit 1;\
 	fi
+	@if [ "$(SKEL_TRGPROJDIR)" = "" ]; then\
+		echo "make skel FAILED: need SKEL_TRGPROJDIR";\
+	 	$(MAKE) --no-print-directory skel-usage_;\
+	 	exit 1;\
+	fi
+	@if [ "$(SKEL_TRGPROJName)" = "" ]; then\
+		echo "make skel FAILED: need SKEL_TRGPROJName";\
+	 	$(MAKE) --no-print-directory skel-usage_;\
+	 	exit 1;\
+	fi
+	@if [ -e "$(SKEL_TRGPROJDIR)" ]; then\
+		echo "make skel FAILED because directory $(SKEL_TRGPROJDIR) already exists";\
+	 	exit 1;\
+	fi
+	@echo "Building Project $(SKEL_TRGPROJName) in $(SKEL_TRGPROJDIR) from sample $(SKEL_SRCPROJDIR)"
+	@mkdir $(SKEL_TRGPROJDIR)
+	@cp -r $(SKEL_SRCPROJDIR) $(SKEL_TRGPROJDIR)/$(SKEL_TRGPROJName);
+	@mkdir -p $(SKEL_TRGPROJDIR)/IntermediateFiles/DefaultConfiguration;
+	#ln -s ../../Projects/Linux/Makefile $(SKEL_TRGPROJName)/IntermediateFiles/DefaultConfiguration/Makefile;
+	@cp Skel/Makefile.skel $(SKEL_TRGPROJDIR)/$(SKEL_TRGPROJName)/Projects/Linux/Makefile;
 
