Progres on make skel support - can almost clone a nearly working vs studio project

diff --git a/Samples/Makefile b/Samples/Makefile
--- a/Samples/Makefile
+++ b/Samples/Makefile
@@ -14,6 +14,7 @@ endif
 SKEL_SRCPROJDIR?=
 SKEL_TRGPROJDir?=
 SKEL_TRGPROJName?=
+SKEL_PATH2Stroika?=
 
 help:
 	@echo "Help for making Stroika"
@@ -43,9 +44,9 @@ samples:
 
 
 skel-usage_:
-	@echo "\tUsage: make skel SKEL_SRCPROJDIR=XX SKEL_TRGPROJDIR=XX SKEL_TRGPROJName=XX"
+	@echo "\tUsage: make skel SKEL_SRCPROJDIR=XX SKEL_TRGPROJDIR=XX SKEL_TRGPROJName=XX SKEL_PATH2Stroika=XX"
 	@echo "\t\tSKEL_SRCPROJDIR is the sample you wisht to clone"
-	@echo "\t\tEG: make skel SKEL_SRCPROJDIR=WebServer SKEL_TRGPROJDIR=./SAMPLEOUT SKEL_TRGPROJName=CLONED_WS"
+	@echo "\t\tEG: make skel SKEL_SRCPROJDIR=WebServer SKEL_TRGPROJDIR=./SAMPLEOUT SKEL_TRGPROJName=CLONED_WS SKEL_PATH2Stroika=..\/..\/..\/..\/.."
 
 skel:
 	@if [ "$(SKEL_SRCPROJDIR)" = "" ]; then\
@@ -63,14 +64,31 @@ skel:
 	 	$(MAKE) --no-print-directory skel-usage_;\
 	 	exit 1;\
 	fi
+	@if [ "$(SKEL_PATH2Stroika)" = "" ]; then\
+		echo "make skel FAILED: need SKEL_PATH2Stroika";\
+	 	$(MAKE) --no-print-directory skel-usage_;\
+	 	exit 1;\
+	fi
 	@if [ -e "$(SKEL_TRGPROJDIR)" ]; then\
 		echo "make skel FAILED because directory $(SKEL_TRGPROJDIR) already exists";\
 	 	exit 1;\
 	fi
 	@echo "Building Project $(SKEL_TRGPROJName) in $(SKEL_TRGPROJDIR) from sample $(SKEL_SRCPROJDIR)"
-	@mkdir $(SKEL_TRGPROJDIR)
-	@cp -r $(SKEL_SRCPROJDIR) $(SKEL_TRGPROJDIR)/$(SKEL_TRGPROJName);
+	
+	@mkdir -p $(SKEL_TRGPROJDIR)/$(SKEL_TRGPROJName)
+	@mkdir -p $(SKEL_TRGPROJDIR)/$(SKEL_TRGPROJName)/Sources
+	@cp -r $(SKEL_SRCPROJDIR)/Sources $(SKEL_TRGPROJDIR)/$(SKEL_TRGPROJName)/
+
+	@mkdir -p $(SKEL_TRGPROJDIR)/$(SKEL_TRGPROJName)/Projects/Linux/
+	@cp Skel/Makefile.skel $(SKEL_TRGPROJDIR)/$(SKEL_TRGPROJName)/Projects/Linux/Makefile;
+
 	@mkdir -p $(SKEL_TRGPROJDIR)/IntermediateFiles/DefaultConfiguration;
 	#ln -s ../../Projects/Linux/Makefile $(SKEL_TRGPROJName)/IntermediateFiles/DefaultConfiguration/Makefile;
-	@cp Skel/Makefile.skel $(SKEL_TRGPROJDIR)/$(SKEL_TRGPROJName)/Projects/Linux/Makefile;
+	
+	@mkdir -p $(SKEL_TRGPROJDIR)/$(SKEL_TRGPROJName)/Projects/VisualStudio.Net-2013/
+	sed s/TEMPLATE/$(SKEL_TRGPROJName)/g < Skel/Projects/VisualStudio.Net-2013/TEMPLATE.sln > $(SKEL_TRGPROJDIR)/$(SKEL_TRGPROJName)/Projects/VisualStudio.Net-2013/$(SKEL_TRGPROJName).sln.tmp
+	sed s/PATH2STROIKA/'$(SKEL_PATH2Stroika)'/g <$(SKEL_TRGPROJDIR)/$(SKEL_TRGPROJName)/Projects/VisualStudio.Net-2013/$(SKEL_TRGPROJName).sln.tmp > $(SKEL_TRGPROJDIR)/$(SKEL_TRGPROJName)/Projects/VisualStudio.Net-2013/$(SKEL_TRGPROJName).sln
+	rm $(SKEL_TRGPROJDIR)/$(SKEL_TRGPROJName)/Projects/VisualStudio.Net-2013/$(SKEL_TRGPROJName).sln.tmp
+	@sed s/TEMPLATE/$(SKEL_TRGPROJName)/g < Skel/Projects/VisualStudio.Net-2013/TEMPLATE.vcxproj > $(SKEL_TRGPROJDIR)/$(SKEL_TRGPROJName)/Projects/VisualStudio.Net-2013/$(SKEL_TRGPROJName).vcxproj
+	@sed s/TEMPLATE/$(SKEL_TRGPROJName)/g < Skel/Projects/VisualStudio.Net-2013/TEMPLATE.vcxproj.filters > $(SKEL_TRGPROJDIR)/$(SKEL_TRGPROJName)/Projects/VisualStudio.Net-2013/$(SKEL_TRGPROJName).vcxproj.filters
 
