fixed OpenSSL makefile to copy data to top-level output folder

diff --git a/ThirdPartyLibs/openssl/Makefile b/ThirdPartyLibs/openssl/Makefile
--- a/ThirdPartyLibs/openssl/Makefile
+++ b/ThirdPartyLibs/openssl/Makefile
@@ -11,8 +11,56 @@ EXTRACTED_DIRNAME=$(BASENAME)
 ZIPEDFILE=../Origs-Cache/$(BASENAME).tar.gz
 
 FETCHURL=http://www.openssl.org/source/$(BASENAME).tar.gz
-
+	
 UNAME := $(shell uname)
+
+BUILDS_ROOT=../../Builds/
+
+ifeq (,$(findstring CYGWIN,$(UNAME)))
+PRODUCED_OUTPUT_ARTIFACTS=	\
+	$(BUILDS_ROOT)DefaultConfiguration/ThirdPartyLibs/libcrypto.a			\
+	$(BUILDS_ROOT)DefaultConfiguration/ThirdPartyLibs/libssl.a				\
+	$(BUILDS_ROOT)DefaultConfiguration/ThirdPartyLibs/openssl				\
+	$(BUILDS_ROOT)DefaultConfiguration/ThirdPartyLibs/includes/openssl/aes.h
+else
+PRODUCED_OUTPUT_ARTIFACTS=	\
+	$(BUILDS_ROOT)Debug-U-32/ThirdPartyLibs/libeay32.lib						\
+	$(BUILDS_ROOT)Debug-U-32/ThirdPartyLibs/ssleay32.lib						\
+	$(BUILDS_ROOT)Debug-U-32/ThirdPartyLibs/openssl.exe						\
+	$(BUILDS_ROOT)Debug-U-32/ThirdPartyLibs/openssl.pdb						\
+	$(BUILDS_ROOT)Debug-U-32/ThirdPartyLibs/includes/openssl/aes.h				\
+	$(BUILDS_ROOT)Release-U-32/ThirdPartyLibs/libeay32.lib						\
+	$(BUILDS_ROOT)Release-U-32/ThirdPartyLibs/ssleay32.lib						\
+	$(BUILDS_ROOT)Release-U-32/ThirdPartyLibs/openssl.exe						\
+	$(BUILDS_ROOT)Release-U-32/ThirdPartyLibs/openssl.pdb						\
+	$(BUILDS_ROOT)Release-U-32/ThirdPartyLibs/includes/openssl/aes.h				\
+	$(BUILDS_ROOT)Release-DbgMemLeaks-U-32/ThirdPartyLibs/libeay32.lib			\
+	$(BUILDS_ROOT)Release-DbgMemLeaks-U-32/ThirdPartyLibs/ssleay32.lib			\
+	$(BUILDS_ROOT)Release-DbgMemLeaks-U-32/ThirdPartyLibs/openssl.exe			\
+	$(BUILDS_ROOT)Release-DbgMemLeaks-U-32/ThirdPartyLibs/openssl.pdb			\
+	$(BUILDS_ROOT)Release-DbgMemLeaks-U-32/ThirdPartyLibs/includes/openssl/aes.h	\
+	$(BUILDS_ROOT)Release-Logging-U-32/ThirdPartyLibs/libeay32.lib				\
+	$(BUILDS_ROOT)Release-Logging-U-32/ThirdPartyLibs/ssleay32.lib				\
+	$(BUILDS_ROOT)Release-Logging-U-32/ThirdPartyLibs/openssl.exe				\
+	$(BUILDS_ROOT)Release-Logging-U-32/ThirdPartyLibs/openssl.pdb				\
+	$(BUILDS_ROOT)Release-Logging-U-32/ThirdPartyLibs/includes/openssl/aes.h		\
+	$(BUILDS_ROOT)Debug-U-64/ThirdPartyLibs/libeay32.lib						\
+	$(BUILDS_ROOT)Debug-U-64/ThirdPartyLibs/ssleay32.lib						\
+	$(BUILDS_ROOT)Debug-U-64/ThirdPartyLibs/openssl.exe						\
+	$(BUILDS_ROOT)Debug-U-64/ThirdPartyLibs/openssl.pdb						\
+	$(BUILDS_ROOT)Debug-U-64/ThirdPartyLibs/includes/openssl/aes.h				\
+	$(BUILDS_ROOT)Release-U-64/ThirdPartyLibs/libeay32.lib						\
+	$(BUILDS_ROOT)Release-U-64/ThirdPartyLibs/ssleay32.lib						\
+	$(BUILDS_ROOT)Release-U-64/ThirdPartyLibs/openssl.exe						\
+	$(BUILDS_ROOT)Release-U-64/ThirdPartyLibs/openssl.pdb						\
+	$(BUILDS_ROOT)Release-U-64/ThirdPartyLibs/includes/openssl/aes.h				\
+	$(BUILDS_ROOT)Release-Logging-U-64/ThirdPartyLibs/libeay32.lib				\
+	$(BUILDS_ROOT)Release-Logging-U-64/ThirdPartyLibs/ssleay32.lib				\
+	$(BUILDS_ROOT)Release-Logging-U-64/ThirdPartyLibs/openssl.exe				\
+	$(BUILDS_ROOT)Release-Logging-U-64/ThirdPartyLibs/openssl.pdb				\
+	$(BUILDS_ROOT)Release-Logging-U-64/ThirdPartyLibs/includes/openssl/aes.h
+endif
+
 
 # COULD make this conditional
 STRIP_ANNOYING_MESSAGES=		1
@@ -30,7 +78,14 @@ clobber:	clean
 	@rm -f BUILD.OUT
 
 check:
-	@./checkall_.pl
+	@echo -n "   ...Checking..."
+	@for i in $(PRODUCED_OUTPUT_ARTIFACTS) ; do \
+		if [ ! -e $$i ]; then\
+			echo "   FAILED: missing $$i";\
+			exit 1;\
+		fi;\
+	done
+	@echo "   Stroika/ThirdPartyLibs/OpenSSL - [Succeeded]";
 
 $(ZIPEDFILE):
 	@echo -n "   ..." 
@@ -72,6 +127,18 @@ doBuilds:
 		echo "   ...Buidling, and redirecting messages to BUILD.OUT ...";\
 		./buildall_.pl > BUILD.OUT 2>&1;\
 	fi
+	@echo "   ...Copying builds to ... $(BUILDS_ROOT)"
+ifeq (,$(findstring CYGWIN,$(shell uname)))
+	@mkdir -p $(BUILDS_ROOT)DefaultConfiguration/ThirdPartyLibs && cp CURRENT/libcrypto.a CURRENT/libssl.a CURRENT/app/openssl $(BUILDS_ROOT)DefaultConfiguration/ThirdPartyLibs/
+else
+	@mkdir -p $(BUILDS_ROOT)Debug-U-32/ThirdPartyLibs && cp -r CURRENT/Builds/Debug32/* $(BUILDS_ROOT)Debug-U-32/ThirdPartyLibs/
+	@mkdir -p $(BUILDS_ROOT)Release-U-32/ThirdPartyLibs && cp -r CURRENT/Builds/Release32/* $(BUILDS_ROOT)Release-U-32/ThirdPartyLibs/
+	@mkdir -p $(BUILDS_ROOT)Release-DbgMemLeaks-U-32/ThirdPartyLibs && cp -r CURRENT/Builds/Release32/* $(BUILDS_ROOT)Release-DbgMemLeaks-U-32/ThirdPartyLibs/
+	@mkdir -p $(BUILDS_ROOT)Release-Logging-U-32/ThirdPartyLibs && cp -r CURRENT/Builds/Release32/* $(BUILDS_ROOT)Release-Logging-U-32/ThirdPartyLibs/
+	@mkdir -p $(BUILDS_ROOT)Debug-U-64/ThirdPartyLibs && cp -r CURRENT/Builds/Debug64/* $(BUILDS_ROOT)Debug-U-64/ThirdPartyLibs/
+	@mkdir -p $(BUILDS_ROOT)Release-U-64/ThirdPartyLibs && cp -r CURRENT/Builds/Release64/* $(BUILDS_ROOT)Release-U-64/ThirdPartyLibs/
+	@mkdir -p $(BUILDS_ROOT)Release-Logging-U-64/ThirdPartyLibs && cp -r CURRENT/Builds/Release64/* $(BUILDS_ROOT)Release-Logging-U-64/ThirdPartyLibs/
+endif
 
 
 ORIG:	$(ZIPEDFILE)
