polish workaround to macos issue with github actions and artifact upload/env vars, and applied same changes to release branch workflow

diff --git a/.github/workflows/build-N-test-MacOS-v2.1-Dev.yml b/.github/workflows/build-N-test-MacOS-v2.1-Dev.yml
--- a/.github/workflows/build-N-test-MacOS-v2.1-Dev.yml
+++ b/.github/workflows/build-N-test-MacOS-v2.1-Dev.yml
@@ -82,12 +82,10 @@ jobs:
           printenv
           echo "TMPDIR"
           echo $TMPDIR
-          echo "TMPDIR using ENV.TMPDIR="
-          # Just the echo line here causes GitHub-Actions-MacOS to die here...
-          #echo ${{ env.TMPDIR }}
+          echo "TMPDIR using ENV.TMPDIR=${{ env.TMPDIR }}"
+          # Just the echo line above shows empty, and then the ls line causes exit 1/failure
           #ls -l ${{ env.TMPDIR }}/Trace*.txt
       - name: Build System Info
-        shell: bash
         run: |
           df -h
       - name: Archive Log Results
diff --git a/.github/workflows/build-N-test-MacOS-v2.1-Release.yml b/.github/workflows/build-N-test-MacOS-v2.1-Release.yml
--- a/.github/workflows/build-N-test-MacOS-v2.1-Release.yml
+++ b/.github/workflows/build-N-test-MacOS-v2.1-Release.yml
@@ -73,16 +73,29 @@ jobs:
       - name: Run-Tests
         run: |
           make run-tests
+      - name: Workaround GitHub-Actions-MacOS Issue with env.TMPDIR
+        run: |
+          mkdir /tmp/LOGS-ARCHIVE
+          cp $TMPDIR/Trace*.txt /tmp/LOGS-ARCHIVE
+      - name: DEBUG Workaround GitHub-Actions-MacOS Issue with env.TMPDIR
+        run: |
+          printenv
+          echo "TMPDIR"
+          echo $TMPDIR
+          echo "TMPDIR using ENV.TMPDIR=${{ env.TMPDIR }}"
+          # Just the echo line above shows empty, and then the ls line causes exit 1/failure
+          #ls -l ${{ env.TMPDIR }}/Trace*.txt
       - name: Build System Info
         run: |
           df -h
-      - name: Archive Performance Log Results
+      - name: Archive Log Results
         uses: actions/upload-artifact@v2
         with:
           name: Log Results (${{ matrix.displayTargetName }})
           path: |
             Builds/${{ matrix.config_name }}/PerformanceDump.txt
-            $TMPDIR/Trace*.txt
+            /tmp/LOGS-ARCHIVE
+            #${{ env.TMPDIR }}/Trace*.txt
       - name: Archive Sample Results
         uses: actions/upload-artifact@v2
         with:
