merged windows and linux and macos (DEV) workflows all into one workflow with different job names)

diff --git a/.github/workflows/build-N-test-Linux-v2.1-Dev.yml b/.github/workflows/build-N-test-Linux-v2.1-Dev.yml
--- a/.github/workflows/build-N-test-Linux-v2.1-Dev.yml
+++ b/.github/workflows/build-N-test-Linux-v2.1-Dev.yml
@@ -11,7 +11,7 @@
 # but none seem to work
 #
 
-name: build-N-test-Linux-v2.1-Dev
+name: build-N-test-v2.1-Dev
 
 on:
   push:
@@ -28,7 +28,7 @@ on:
 ## NB: JOBS section IDENTICAL between v2.1-Dev and 2.1-Release files EXCEPT that on v2.1-Dev file
 ## comment out all entries marked with includeInDevBranchBuilds: false
 jobs:
-  build-n-test:
+  build-n-test-Linux:
     runs-on: ${{ matrix.runs_on }}
     strategy:
       matrix:
@@ -171,3 +171,193 @@ jobs:
           path: |
             Builds/${{ matrix.config_name }}/PerformanceDump.txt
             /tmp/Trace*.txt
+
+  build-n-test-MacOS:
+    runs-on: ${{ matrix.runs_on }}
+    strategy:
+      matrix:
+        # Add to extra_config_args for build speed: --Xerces no --OpenSSL no --lzma no --boost no
+        include:
+          - displayTargetName: MacOS-Debug
+            os: macos-10.15
+            runs_on: macos-10.15
+            config_name: Debug
+            extra_config_args: --apply-default-debug-flags --trace2file enable
+            includeInDevBranchBuilds: true
+          # - displayTargetName: MacOS
+          #   os: macos-10.15
+          #   runs_on: macos-10.15
+          #   config_name: Release
+          #   extra_config_args: --apply-default-release-flags --trace2file enable
+          #   includeInDevBranchBuilds: false
+    env:
+      # vm has 2 virtual CPUs, but 8GB ram, so jobs=5 (empirical), and QUICK_BUILD avoids some internal testing
+      MAKEFLAGS: "--jobs=3 QUICK_BUILD=1"
+    steps:
+      - uses: actions/checkout@v2
+      - name: Build System Info
+        run: |
+          echo "CWD: `pwd`"
+          df -h
+          system_profiler SPSoftwareDataType
+          sw_vers
+      # If we had docker ability, most of these would be built into a docker file
+      - name: Install Basic Build requirements
+        run: |
+          brew install gnu-sed
+          brew install p7zip
+          brew install automake
+          make install-realpath
+      - name: Configure
+        run: |
+          ./configure ${{ matrix.config_name }} ${{ matrix.extra_config_args }}
+          cat ConfigurationFiles/${{ matrix.config_name }}.xml
+      - name: Build third-party-components
+        run: |
+          make third-party-components
+          make clean
+      - name: Build Library
+        run: |
+          make libraries
+      - name: Build All
+        run: |
+          make all
+      - name: Run-Tests
+        run: |
+          make run-tests
+      - name: Workaround GitHub-Actions-MacOS Issue with env.TMPDIR
+        run: |
+          mkdir /tmp/LOGS-ARCHIVE
+          cp $TMPDIR/Trace*.txt /tmp/LOGS-ARCHIVE
+      - name: DEBUG Workaround GitHub-Actions-MacOS Issue with env.TMPDIR
+        run: |
+          echo "TMPDIR=$TMPDIR"
+          echo "TMPDIR using ENV.TMPDIR=${{ env.TMPDIR }}"
+          # Just the echo line above shows empty, and then the ls line causes exit 1/failure
+          #ls -l ${{ env.TMPDIR }}/Trace*.txt
+          #if this gets fixed, then lose Workaround GitHub-Actions-MacOS, and directly reference ${{ env.TMPDIR }}/Trace*.txt in Archive Log Results
+      - name: Build System Info
+        run: |
+          df -h
+      - name: Archive Log Results
+        uses: actions/upload-artifact@v2
+        with:
+          name: Log Results (${{ matrix.displayTargetName }})
+          path: |
+            Builds/${{ matrix.config_name }}/PerformanceDump.txt
+            /tmp/LOGS-ARCHIVE
+            #${{ env.TMPDIR }}/Trace*.txt
+      - name: Archive Sample Results
+        uses: actions/upload-artifact@v2
+        with:
+          name: Samples (${{ matrix.displayTargetName }})
+          path: |
+            Builds/${{ matrix.config_name }}/Samples-*
+
+  build-n-test-Windows:
+    runs-on: ${{ matrix.runs_on }}
+    strategy:
+      matrix:
+        # Add to extra_config_args for build speed: --Xerces no --OpenSSL no --lzma no --boost no
+        include:
+          - displayTargetName: windows-x86-Debug
+            os: windows
+            runs_on: windows-latest
+            container_image: sophistsolutionsinc/stroika-buildvm-windows-cygwin-vs2k19
+            config_name: Debug
+            extra_config_args: --arch x86 --apply-default-debug-flags --trace2file enable
+            includeInDevBranchBuilds: true
+          # - displayTargetName: windows-x86-Release
+          #   os: windows
+          #   runs_on: windows-latest
+          #   container_image: sophistsolutionsinc/stroika-buildvm-windows-cygwin-vs2k19
+          #   config_name: Release
+          #   extra_config_args: --arch x86 --apply-default-release-flags --trace2file enable
+          #   includeInDevBranchBuilds: false
+          # - displayTargetName: windows-x86_64-Debug
+          #   os: windows
+          #   runs_on: windows-latest
+          #   container_image: sophistsolutionsinc/stroika-buildvm-windows-cygwin-vs2k19
+          #   config_name: Debug
+          #   extra_config_args: --arch x86_64 --apply-default-debug-flags --trace2file enable
+          #   includeInDevBranchBuilds: false
+          # - displayTargetName: windows-x86_64-Release
+          #   os: windows
+          #   runs_on: windows-latest
+          #   container_image: sophistsolutionsinc/stroika-buildvm-windows-cygwin-vs2k19
+          #   config_name: Release
+          #   extra_config_args: --arch x86 --apply-default-release-flags --trace2file enable
+          #   includeInDevBranchBuilds: false
+    env:
+      # vm has 2 virtual CPUs, but 8GB ram, so jobs=5 (empirical), and QUICK_BUILD avoids some internal testing
+      MAKEFLAGS: "--jobs=3 QUICK_BUILD=1"
+      ARTIFACTS_DIR: "c:/Artifacts/"
+    steps:
+      - uses: actions/checkout@v2
+      # https://stackoverflow.com/questions/58033366/how-to-get-current-branch-within-github-actions
+      - name: Extract branch name
+        shell: bash
+        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
+        id: extract_branch
+      - name: Build System Info
+        shell: "bash"
+        run: |
+          echo "CWD: `pwd`"
+          df -h
+          systeminfo
+          echo NUMBER_OF_PROCESSORS=$NUMBER_OF_PROCESSORS
+      - name: docker pull ${{ matrix.container_image }}
+        run: docker pull ${{ matrix.container_image }}
+      - name: Start docker build environment
+        run: |
+          docker run --tty --memory 5G --cpus 2 --storage-opt 'size=50GB' --detach --name buildContainer ${{ matrix.container_image }}
+      - name: Print Info about docker system
+        shell: "bash"
+        run: |
+          docker ps -a
+          docker exec buildContainer systeminfo
+          docker exec buildContainer df -h
+      - name: Git Checkout
+        shell: "bash"
+        run: |
+          docker exec buildContainer sh -c "git clone https://github.com/SophistSolutions/Stroika.git && cd Stroika && git checkout ${{ steps.extract_branch.outputs.branch }}"
+      - name: Configure
+        shell: "bash"
+        run: |
+          docker exec --workdir c:/Stroika buildContainer sh -c "./configure ${{ matrix.config_name }} ${{ matrix.extra_config_args }}"
+          docker exec --workdir c:/Stroika buildContainer cat ConfigurationFiles/${{ matrix.config_name }}.xml
+      - name: Build
+        shell: "bash"
+        run: |
+          docker exec --workdir c:/Stroika --env MAKEFLAGS="$MAKEFLAGS" buildContainer make all
+      - name: Run-Tests
+        shell: "bash"
+        run: |
+          docker exec --workdir c:/Stroika --env MAKEFLAGS="$MAKEFLAGS" buildContainer make run-tests
+      - name: Build System Info
+        shell: "bash"
+        run: |
+          df -h
+          docker exec buildContainer df -h
+      - name: Copy Build Artifacts
+        shell: "bash"
+        # due to flaws in docker (windows must stop) - and cp no wildcards
+        run: |
+          docker exec --workdir c:/Stroika buildContainer bash -c 'mkdir TRACE_LOGS && cp $TEMP/Trace*.txt TRACE_LOGS/'
+          docker stop buildContainer
+          docker cp buildContainer:Stroika/Builds/${{ matrix.config_name }}/ $ARTIFACTS_DIR 2> /dev/null
+          docker cp buildContainer:Stroika/TRACE_LOGS $ARTIFACTS_DIR 2> /dev/null
+          rm -rf $ARTIFACTS_DIR/{ThirdPartyComponents,Tests,*.lib}
+      - name: Archive Log Results
+        uses: actions/upload-artifact@v2
+        with:
+          name: Log Results (${{ matrix.displayTargetName }})
+          path: |
+            ${{ env.ARTIFACTS_DIR }}PerformanceDump.txt
+            ${{ env.ARTIFACTS_DIR }}TRACE_LOGS
+      - name: Archive Sample Results
+        uses: actions/upload-artifact@v2
+        with:
+          name: Samples (${{ matrix.displayTargetName }})
+          path: |
+            ${{ env.ARTIFACTS_DIR }}Samples-*
