debug github action dump log data (windows)

diff --git a/.github/workflows/build-N-test.yml b/.github/workflows/build-N-test.yml
--- a/.github/workflows/build-N-test.yml
+++ b/.github/workflows/build-N-test.yml
@@ -337,11 +337,14 @@ jobs:
           # (except $TMPDIR: Just copy out from container the stuff in /tmp)
           (docker exec --workdir c:/ buildContainer bash -c 'mkdir -p c:/TRACE_LOGS; cp $TEMP/Trace*.txt c:/TRACE_LOGS/') || :
           docker stop buildContainer
-          (docker cp "buildContainer:c:/TRACE_LOGS/" $ARTIFACTS_DIR) || echo "error copying tracelogs ignored"
+          (docker cp "buildContainer:c:/TRACE_LOGS/" $ARTIFACTS_DIR/TRACE_LOGS/) || echo "error copying tracelogs ignored"
           echo "${GITHUB_WORKSPACE}/Builds/${{ matrix.config_name }}/" $ARTIFACTS_DIR
           echo gothere 2.2
+          ls -l $ARTIFACTS_DIR/
           (cp -r --dereference "${GITHUB_WORKSPACE}/Builds/${{ matrix.config_name }}/" $ARTIFACTS_DIR) || echo "error copying builds ignored"
           echo got here3
+          ls -l $ARTIFACTS_DIR/
+          echo got here3.1
           ls -l "${GITHUB_WORKSPACE}/Builds/${{ matrix.config_name }}/"
           rm -rf $ARTIFACTS_DIR/{ThirdPartyComponents,Tests,*.lib}
           echo got here4
